"""Infrastructure layer: concrete adapters implementing the domain ports."""

from .array_ops import (
    CROSSOVER_MIN_CLASSES,
    CROSSOVER_MIN_ITEMS,
    NumpyArrayOps,
    resolve_array_backend,
)
from .encoder import (
    HashingEncoder,
    SentenceTransformerEncoder,
    TfidfEncoder,
    fit_tfidf_encoder,
    train_encoder,
)
from .feature_providers import ClassKeywordOverlapProvider
from .fusion import (
    BetaCalibrator,
    IsotonicCalibrator,
    LightGBMFusionModel,
    PlattCalibrator,
    XGBoostFusionModel,
    XGBRankerFusionModel,
)
from .persistence import ArtifactRepository, DeployedArtifacts
from .registry import (
    ArrayOpsSpec,
    CalibratorSpec,
    DenseRetrieverSpec,
    EncoderSpec,
    FeatureProviderSpec,
    FusionSpec,
    LexicalRetrieverSpec,
    SignalProviderSpec,
    array_ops_spec,
    build_array_ops,
    build_calibrator,
    build_dense_retriever,
    build_encoder,
    build_feature_providers,
    build_fusion,
    build_lexical_retriever,
    build_signal_providers,
    dense_retriever_spec,
    encoder_is_corpus_dependent,
    fit_encoder,
    lexical_retriever_spec,
    load_signal_providers,
    register_array_ops,
    register_calibrator,
    register_dense_retriever,
    register_encoder,
    register_feature_provider,
    register_fusion,
    register_lexical_retriever,
    register_signal_provider,
    registered_array_ops_kinds,
    signal_provider_spec,
)
from .retrieval import (
    BM25Index,
    DenseRetrieverAdapter,
    DenseState,
    LexicalRetrieverAdapter,
    bm25_prunes_vocab,
)
from .signals import DenseSignalProvider, LexicalSignalProvider

__all__ = [
    "SentenceTransformerEncoder",
    "TfidfEncoder",
    "HashingEncoder",
    "train_encoder",
    "fit_tfidf_encoder",
    "BM25Index",
    "DenseRetrieverAdapter",
    "DenseState",
    "LexicalRetrieverAdapter",
    "bm25_prunes_vocab",
    "XGBoostFusionModel",
    "LightGBMFusionModel",
    "XGBRankerFusionModel",
    "IsotonicCalibrator",
    "PlattCalibrator",
    "BetaCalibrator",
    "ArtifactRepository",
    "DeployedArtifacts",
    "ClassKeywordOverlapProvider",
    "EncoderSpec",
    "FusionSpec",
    "CalibratorSpec",
    "FeatureProviderSpec",
    "build_encoder",
    "build_fusion",
    "build_calibrator",
    "build_feature_providers",
    "encoder_is_corpus_dependent",
    "fit_encoder",
    "register_encoder",
    "register_fusion",
    "register_calibrator",
    "register_feature_provider",
    "NumpyArrayOps",
    "resolve_array_backend",
    "CROSSOVER_MIN_ITEMS",
    "CROSSOVER_MIN_CLASSES",
    "ArrayOpsSpec",
    "array_ops_spec",
    "build_array_ops",
    "register_array_ops",
    "registered_array_ops_kinds",
    "DenseRetrieverSpec",
    "LexicalRetrieverSpec",
    "build_dense_retriever",
    "build_lexical_retriever",
    "dense_retriever_spec",
    "lexical_retriever_spec",
    "register_dense_retriever",
    "register_lexical_retriever",
    "SignalProviderSpec",
    "DenseSignalProvider",
    "LexicalSignalProvider",
    "build_signal_providers",
    "load_signal_providers",
    "register_signal_provider",
    "signal_provider_spec",
]
